### ISSUE TITLE
[Feature] Metadata Search in Public api endpoint

### ISSUE THREAD

**Issue by JPVenson** [beatmaps-io/beatsaver-main#100]
The /search/text/page endpoint allows an undefined q= query parameter, but for my project it would be great if you could add explicit search for the included metadata 

```
{
metadata: 
   {
   bpm: 126.15
   duration: 262
   levelAuthorName: "Majorpickle"
   songAuthorName: "Robert Tepper"
   songName: "No Easy Way Out"
   songSubName: ""
   }
}
```

Most interestingly would be the inclusion of:
- songAuthorName
- songName
- songSubName

**Comment by Top-Cat** [comment]
Not possible without adding a load of indexes just for you -> not practical

**Comment by Top-Cat** [comment]
If your project needs more complex search mirror the data you need into your own indexes
