### ISSUE TITLE
recaptcha problem

### ISSUE THREAD

**Issue by itsdarkelitus** [beatmaps-io/beatsaver-main#101]
hello im trying to upload my map but when i try to upload i get this error in the console: 

![image](https://user-images.githubusercontent.com/87384999/162615386-cf82eed6-91b9-4ffa-a3c5-8762d3f1d3fb.png)

**Comment by Top-Cat** [comment]
Don't know what you want me to do about that, if it's a recaptcha error you should report it to google/recaptcha?
afaik other people are uploading maps fine
