### ISSUE TITLE
WebSocket sends information for maps that are not yet public

### ISSUE THREAD

**Issue by MrMineO5** [beatmaps-io/beatsaver-main#104]
The title says it all, when using the WebSocket component of the API, you receive map updates for maps that are not yet public, these updates include the download URL and all information usually available through the API. This undermines the fact that the maps are not shown in the actual API yet.

**Comment by Top-Cat** [comment]
As designed, maps you upload aren't private. The change to hide the pages on the site during this phase was only to prevent people using it to distribute WIPs until we come up with a better solution for storing / deleting maps that never get published.
