### ISSUE TITLE
[Suggestion] Excluding style/genre tags

### ISSUE THREAD

**Issue by Pixelguymm** [beatmaps-io/beatsaver-main#109]
As BoostOrDie#1152 on Discord pointed out, there's no way to exclude certain tags from search. I think the following would work pretty well:
- Left-clicking will select multiple tags by default. If people only want one tag, they can just click the ones they had previously selected.
- Shift + left-click will exclude tags, highlighting them in red.

Additionally, it might be better to find maps that have any of the selected tags, instead of all of them. This seems to have more use cases, and is the behavior that most people, including me, would expect.

**Comment by Pixelguymm** [comment]
> To be clear shift + click already allows you to select multiple tags / remove individual tags from what is selected.

I'm aware, but most people aren't. I feel like the behavior I suggested would also make more sense if my final point were to be implemented.

> especially if using a key that currently does something else.

We could use CTRL if you prefer, though CTRL is most commonly used for multi-selecting rather than shift.

> As for finding using any rather than all, I don't know why you would expect that. It's not how any of the other filters work.

I feel like tags are different? When selecting 2 tags, the query will only return a small number of results, and selecting more than 2 shouldn't technically return any at all. If we select maps including *any* of the selected tags, more results would be returned. You could just select all of the genres you like and get plenty of maps to choose from.

That said, I think difficulty tags are a bit different. Selecting maps with any of the genre tags *or* any of the difficulty tags will return very inaccurate results, so it should probably find maps with any of the genre tags *and* any of the difficulty tags instead.

**Comment by Top-Cat** [comment]
With the final comment there you're straying into very probable performance issues, anything to do with search needs to consider how it's going to perform filtering tens of thousands of records.

**Comment by Pixelguymm** [comment]
Good point, how bad are we talking? Are the performance issues something we're able to solve/improve?

**Comment by Top-Cat** [comment]
Probably better to try and generate yourself some test data and see if you're looking to move forward with this yourself

**Comment by Top-Cat** [comment]
This is done I think?
