### ISSUE TITLE
Restrict uploader names to alphanumeric chars or add a new field

### ISSUE THREAD

**Issue by n3tman** [beatmaps-io/beatsaver-main#11]
Previous username rules by Jellyfish (from `#modding-announcements`)
> Usernames may now only include alphanumeric characters or a `-` character.

Any string in a username doesn't allow to create URL-friendly post tags on BSaber.

Example uploader: https://beatsaver.com/profile/4284389
Current `uploader.name` from the API: `AndroGeek | Beat Saber Mapper`
Previously it was just `androgeek`: https://bsaber.com/tag/androgeek/

A possible solution would be to ask users who logged in through Discord to enter a separate name that follows old naming rules.

**Comment by Top-Cat** [comment]
Users are now being asked to pick a name that matches `^[\._\-A-Za-z0-9]{3,}$`
Anyone who had linked an old beatsaver account has it pre-filled but it's going to take some time for discord-only accounts to get filled in
