### ISSUE TITLE
[Suggestion] Add 1.20+ tag or AnC tag for new features of bs maps

### ISSUE THREAD

**Issue by Dieber** [beatmaps-io/beatsaver-main#110]
I think most of us want to filter songs which are support Arc and Chain...
I also can contribute some code but I have to get acquainted with kotlin some how..
so will you guys add this feature in this site? 
regards.

**Comment by Top-Cat** [comment]
Not really a useful feature once editors properly support these features, it'll just be every map. For now probably just look at https://beatsaver.com/playlists/4042
