### ISSUE TITLE
[Suggestion] Change downvote display on bar from Red to Black

### ISSUE THREAD

**Issue by AliceXIV** [beatmaps-io/beatsaver-main#112]
As a contributor, having ratios be displayed as green/red bars is discouraging. People subconsciously associate red with danger/aggression, and red stands out more than green.

Red/Green is also a common colorblindness combination, which makes the bar difficult to use as both colors have similar saturation.

Here's a mock-up of my own profile with the red bar replaced with `#111`:
![image](https://user-images.githubusercontent.com/59019761/168308086-75855932-1f55-42f1-901b-c61937fd0ae4.png)

I don't know how to use GIT but this is where the change would be:
https://github.com/beatmaps-io/beatsaver-main/blob/de725c6bc9108b23ae3d57799caf3dfc4dd9621e/src/jvmMain/sass/main.scss#L198

It's a quick fix that can be applied with minimal change and I think it will address some of the negativity.

**Comment by XAce1337manX** [comment]
Good idea. Though imo black is a bit too jarring especially larger black areas.
![image](https://user-images.githubusercontent.com/68104413/168319994-316d97e9-f198-40b3-8f36-3c24e14ff5bf.png) 
![image](https://user-images.githubusercontent.com/68104413/168320891-154363c3-0f00-4baf-ad69-9fff8590bc7c.png)

Propose `#666` instead. Which still has alright contrast without colours: 
![image](https://user-images.githubusercontent.com/68104413/168320252-cc096a1e-df80-4da0-8ada-3342c3a10603.png)
![image](https://user-images.githubusercontent.com/68104413/168320388-d5693fd9-6351-43fe-be1c-d53c95332880.png)

As a comparison to current green/red colours:
![image](https://user-images.githubusercontent.com/68104413/168320634-d67fca40-9b80-4f7b-9a6a-c7a84fa7de6b.png)
![image](https://user-images.githubusercontent.com/68104413/168321111-b0a41f69-614c-4200-ad51-b9755c6b1133.png)
