### ISSUE TITLE
User registration not fully processing registrations

### ISSUE THREAD

**Issue by helencarnate** [beatmaps-io/beatsaver-main#114]
**Summary:** When registering for a new user account with an email (vs. using Discord), after completing the required information and clicking the registration button, nothing happens.
**Steps to Reproduce:**
1. Go to https://beatsaver.com/register
2. Enter a username, email, and password (x2)
3. Click the register button

**Actual Results:** No action occurs. The account is created somewhere in the DB because the username is consumed, but is not able to be logged in to with the registered credentials.

The following is displayed in the console:
![image](https://user-images.githubusercontent.com/57695406/169628886-4ceecdf5-bdee-4d3b-bd77-ed737ff3222a.png)
**Expected Results:** Redirects to a confirmation screen and/or sends a confirmation email. Account is created and user can login and upload maps.
**Data:**
Discord user Xunac, myself, and Pixelguy all replicated the same results. I registered for an "alt" under username _ApocalypseFrau_. If I try to register with the same username again the site tells me the username is taken, despite being unable to login with the username/email/password I entered.

**Comment by Top-Cat** [comment]
Should be fixed
