### ISSUE TITLE
Uploading maps that use the new BPM tool from the official editor does not work

### ISSUE THREAD

**Issue by Lekrkoekj** [beatmaps-io/beatsaver-main#116]
I made a map using the official editor and its new BPM tool. When I try to upload the map to BeatSaver it gives me these errors:
![image](https://user-images.githubusercontent.com/50798931/170118104-17af502d-c195-44d5-9a10-0606953102ee.png)

It doesn't let me upload the map.

**Comment by helencarnate** [comment]
@Lekrkoekj Can you please provide an example file? Thanks!

**Comment by Lekrkoekj** [comment]
> @Lekrkoekj Can you please provide an example file? Thanks!

Sure, here's the map:
[map.zip](https://github.com/beatmaps-io/beatsaver-main/files/9084270/map.zip)

**Comment by Top-Cat** [comment]
Fixed in beatmaps-io/beatsaver-common-mp@a82f4a0
