### ISSUE TITLE
Feature Request: Descriptions, links and country flag on mapper pages

### ISSUE THREAD

**Issue by helencarnate** [beatmaps-io/beatsaver-main#121]
**Originally posted on the Ideas site by anonymous**  It would be nice for mappers to have a little bio and maybe links to some of their socials to personalize their profiles and allow new players to connect with their favorite mappers! a country flag or location would be a nice bonus too!

**Comment by helencarnate** [comment]
A size-constrained bio that allowed markdown/rich text inputs along with UTF-8 emojis would address this (and allow people who want to show off their country flags to do so with emoji). Can include in a future-state profile page mockup.

**Comment by Top-Cat** [comment]
Closing as we now have descriptions with markdown / emoji to fulfil this requirement.
