### ISSUE TITLE
Feature Request: `web+bsmap` URL protocol handler

### ISSUE THREAD

**Issue by byhemechi** [beatmaps-io/beatsaver-main#123]
ScoreSaber now has a download button which links to `web+bsmap://[map hash]`. Adding a URL procol handler would allow that link to go directly to the map page

**Comment by byhemechi** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Navigator/registerProtocolHandler

**Comment by Top-Cat** [comment]
And why would you do that rather than just have scoresaber link to the map directly?

**Comment by Pixelguymm** [comment]
Yes, but for what reason?
