### ISSUE TITLE
Maps that are AI-assisted are undownloadable

### ISSUE THREAD

**Issue by Devonix07** [beatmaps-io/beatsaver-main#129]
I just tried to download an auto-generated map (both manually and using One-Click) and it didn't work. The map's metadata seems to be completely inaccessible via the site. However, player-made maps are still able to be downloaded without any errors.
Vid 1- me trying to manually download an autogen map
Vid 2- me trying to One-Click Install an autogen map
Vid 3- me trying to download a different autogen map in both ways
Vid 4- a non-autogen map downloading without error

https://user-images.githubusercontent.com/108774160/177448787-c3ea0032-568d-4ecd-b7b0-03b2f65ab5ec.mp4
https://user-images.githubusercontent.com/108774160/177448798-90465b3f-993b-46a8-8646-f7f56268795f.mp4
https://user-images.githubusercontent.com/108774160/177448808-a424efe0-5882-45bb-88a8-391289199252.mp4
https://user-images.githubusercontent.com/108774160/177448815-1b4d8314-7e99-468c-a975-eb1cc7be138f.mp4

**Comment by helencarnate** [comment]
I am able to reproduce from the North America CDN but if you change the URL prefix to eu.cdn it downloads right away.
