### ISSUE TITLE
[Request] Map length on front of the map, contributers tab?

### ISSUE THREAD

**Issue by 3Stans** [beatmaps-io/beatsaver-main#13]
Knowing how long a map is without having to open the map page will probably be helpful in the case I go to search new nekopara maps and get too hyped to check out the map page only to find out the nekopara map was only about 15 seconds long. Though personally it took me a bit to notice the one on the old beatsaver and I wouldn't mind a 15 second long nekopara map, would probably be useful for others from what I've heard

And a contributors tab would, I feel be nice for the cases where a mapper may put playtesters, other mappers/lighters in there but not in the map authors field.

**Comment by helencarnate** [comment]
See Issue #7 for a mock that adds song duration (and other common screening data) to the Map Card.

**Comment by Top-Cat** [comment]
Map length is now visible on the cards.

I would recommend not adding multiple suggestions to a single issue, if you want to flesh out your other suggestion please open a separate issue for it.
