### ISSUE TITLE
Prevent users from scheduling maps to be published on past dates/times

### ISSUE THREAD

**Issue by stillinkansas** [beatmaps-io/beatsaver-main#133]
I was editing and getting my 27b27 map to be published for today (7/12) at 1pm central. I was working on this last night (7/11) at 11:25pm central or so. When I opened the schedule option, I started editing the time assuming that I was working on the 7/12 options. I ended up scheduling my map for 11am central on 7/11 by mistake (I just assumed that wouldn't be possible and that 7/12 would default as the first available date). Once I did this, the map was not publicly available (I think?), but the "Uploaded" data value was set to 11:25pm central on 7/11 (2022-07-12T04:25:00.558558Z).

I then rescheduled the map to release on 7/12 at 1pm central and the map was republished at that time (2022-07-12T18:00:00.559116Z). During this time between the first published time and the second, I think I checked my profile and the map was not published yet, but I can't be sure if I remembered that correctly.

Ultimately, it would be helpful to prevent users from scheduling a map on a date/time that isn't possible to avoid accidentally insta-publishing or creating a fake published date.

**Comment by Top-Cat** [comment]
The scheduledAt value is not used to set the uploaded/published date, this is set to the current time when the map is published

I really prefer letting values in the past work rather than giving the user an error. As the time is auto-filled when opening the publish dialog showing an error 10% of the time because you waited a few seconds and the minutes value changed seems like madness and if you're not doing that you're starting to build arbitrary rules around when is ok and when isn't.

**Comment by stillinkansas** [comment]
The problem is that it didn't "work". My map was effectively published and unpublished instantaneously at 11:25pm central on 7/11. Once I rescheduled it, it was actually published for the first time at 1pm central on 7/12. It was invisible to the public for 13 hours and when it was made visible, it had already moved down the new list a huge distance due to being published "14 hours ago". If that had been 24 hours or multiple days, it would be buried before it ever existed as far as the public was concerned.

**Comment by stillinkansas** [comment]
The main issue I have with it is the publishing and unpublishing part.

If my map had been actually published when I made that mistake, I could easily delete and remake the map if it truly needed to be published at a specific time (like for a pack release in this case). Or I could just leave it published.

**Comment by Top-Cat** [comment]
That's really not how it works.

Sadly this is now only anecdotal evidence. I suggest in future if you have an issue with a map you ask for assistance in #support on discord

**Comment by stillinkansas** [comment]
I literally gave you the key to the map with the issue in the first post. I didn't know it was a problem until after it was published the second time due to the fact that there is no indication of how it works.
