### ISSUE TITLE
"Map already uploaded"

### ISSUE THREAD

**Issue by RedTheFox999** [beatmaps-io/beatsaver-main#135]
I'm trying to upload a beatmap that I previously had up, but it didn't work properly when I tried testing the download. I deleted it and tried to re-upload it, but now it's telling me the map is already uploaded even though I fully deleted it and there are no others like it on BeatSaver. Beatmap in question is for Sainted by the Storm.

**Comment by helencarnate** [comment]
@RedTheFox999 Please use the #support channel on discord for issues like this. This is not a bug, you'll need to change some tiny thing about your map to change the hash. Ping me in the support channel when you see this and I'll answer any other questions you have.
