### ISSUE TITLE
[BUG] When scrolling by pressing on the scroll wheel and moving mouse down with a filter selected all maps flicker

### ISSUE THREAD

**Issue by GoldenNuggo** [beatmaps-io/beatsaver-main#136]
Link to a video showing what I'm saying above since it probably doesn't make sense
https://streamable.com/6k7bk

_**Note**_
The person I was helping out with this seemed to have a fix when they reloaded the page, same fixed for me

**Comment by Top-Cat** [comment]
Video is broken and you've said it fixed itself? 🤷‍♂️
