### ISSUE TITLE
Editing a playlist cover image doesn't seem to be working

### ISSUE THREAD

**Issue by Joetastic2739** [beatmaps-io/beatsaver-main#142]
Pressing edit on a playlist and editing the title and description seems to work. But when uploading a new photo it doesn't show up.
![image](https://user-images.githubusercontent.com/83951411/182025874-52afa5a0-ef2f-4315-a958-79cae2d8131b.png)

**Comment by Top-Cat** [comment]
What image are you seeing? What image are you uploading?

**Comment by Joetastic2739** [comment]
![image](https://user-images.githubusercontent.com/83951411/182329873-128f469a-6c48-4b26-8c10-3308726b933c.png)
Looks like it was a caching issue, it took over a day for it to update on my end
