### ISSUE TITLE
Voting gives server error on Oculus store installation

### ISSUE THREAD

**Issue by symphonic643** [beatmaps-io/beatsaver-main#149]
For the past few months the voting system has not worked at all for me in-game. Most of the time it would just sit there pretending it's doing something but never go through, but most recently it's given me a "server error" situation. This has persisted through several versions and reinstalls of Beat Saber and all of the relevant mods, so I can safely say it's not due to that kind of problem.

**Comment by Top-Cat** [comment]
Can you provide logs / screenshots of the error?

**Comment by symphonic643** [comment]
> Can you provide logs / screenshots of the error?

I'll see if I can grab some next time I'm in game. Where would that show / where can I find the logs that would show that?
