### ISSUE TITLE
_songTimeOffset: Must be equal to 0

### ISSUE THREAD

**Issue by sellorio2** [beatmaps-io/beatsaver-main#150]
Please remove this validation check since it is incorrect.

This validation adds an unnecessary step (and the need for another tool) when mapping. Songs will often be slightly off the beat timing and it is unreasonable to have to edit the audio file for such a minor thing.

_songTimeOffset is supported by Beat Saber and current beat map editors. There's no benefit to preventing the value from being used.

I won't be sharing my maps until this is resolved.

**Comment by Top-Cat** [comment]
_songTimeOffset has historically been responsible for several bugs that to my knowledge are still not entirely resolved so for now you shouldn't use it

Don't know why you think threatening to not share your maps would change anything, you do you

**Comment by sellorio2** [comment]
Still a supported feature in beat saber. Still no reason to block maps. Make it a warning if you like.

**Comment by XAce1337manX** [comment]
Only editor that supports `_songTimeOffset` is CM. Even official editor doesn't support it.
iirc, song offset still has bugs: 
* Negative offset causes notes are invisible during the time added, which makes it unable to fully prevent hot starts.
* Desyncs the song if not played at 100% speed.

**Comment by sellorio2** [comment]
What if beatsaver took the start offset and clipped the audio to match? Obviously extra work on your end and not technically part of your scope but it sure would be a helpful tool. Having to install an audio editing tool and go back and forth trying to get the timing just right is very time consuming and tedious.

**Comment by Top-Cat** [comment]
You don't have to go back and forth. If you follow the community guides there are ways to get it set up correctly first time every time in an audio editor. There's no reason to over-engineer the problem and make beatsaver do that.
