### ISSUE TITLE
UserRating Overview stuck at 0

### ISSUE THREAD

**Issue by ParzivalExe** [beatmaps-io/beatsaver-main#151]
I debated quite a bit weather I should really report this issue as it is pretty minor (and I really don't want to come over as if I need the glory's of a single good review 😅) but in the End this may be a bug that is not contained to one of my songs so: 

On my Song Teeth (https://bsaber.com/songs/28210/) I have one 5/5 User-Rating which shows perfectly in the Page of the Song (although I had one instance where the Review didn't load but that was not reproducible) but when viewing it in a list of Songs (the Cover if you will) (https://bsaber.com/?s=Teeth+-+5+Seconds+of+Summer) it shows a 0 as the overall Rating-Score. At first I thought that this was simply the default for no Ratings but then I realised that the default is actually nothing until ratings are given, so...
My other Song works perfectly so it doesn't seem to be tied to my Account but rather to the specific Song.

**Comment by Top-Cat** [comment]
This is beatsaver not beastsaber

**Comment by ParzivalExe** [comment]
Oh, sorry. I mixed up the two Discords. So sorry, but thanks for the heads up 😬
