### ISSUE TITLE
Playlist page caps at 20

### ISSUE THREAD

**Issue by Joetastic2739** [beatmaps-io/beatsaver-main#155]
The playlist page for each account caps at 20. Meaning any playlist beyond 20 are hidden https://beatsaver.com/profile/58338#playlists

![image](https://user-images.githubusercontent.com/83951411/187413772-e7c3c36c-91d2-4654-bf4e-d1a819bb9ebc.png)

**Comment by Top-Cat** [comment]
Fixed by 239782d
