### ISSUE TITLE
[Request] Direct Download Zip Name Format

### ISSUE THREAD

**Issue by bloodcloak** [beatmaps-io/beatsaver-main#16]
Have the client side download zip option 
![image](https://user-images.githubusercontent.com/59000966/128649702-ca4c02f4-2b35-4747-b056-5346ff392e20.png)

download in the MA format `mapKey (SongName - Mapper)` instead of the hash
https://github.com/Assistant/ModAssistant/blob/9980b42d39de59f7ed3648dbaf76a97fbba6f7ee/ModAssistant/Classes/External%20Interfaces/BeatSaver.cs#L143

with illegal characters being https://github.com/Assistant/ModAssistant/blob/9980b42d39de59f7ed3648dbaf76a97fbba6f7ee/ModAssistant/Classes/Utils.cs#L35

**Comment by Top-Cat** [comment]
Done :)
