### ISSUE TITLE
[Bug] Notes per Second stat is incorrect for maps with official bpm changes

### ISSUE THREAD

**Issue by XAce1337manX** [beatmaps-io/beatsaver-main#160]
The notes per second statistic does not account for official bpm changes scaling time. (i.e the bpm between each beat in the json is not always the bpm in the `Info.dat`.)

Example: https://beatsaver.com/maps/28978
NPS using audio: 4.57
Mapped NPS without factoring bpm changes: 4.08 (This is what's currently displayed on BeatSaver)
Mapped NPS when factoring bpm changes: 4.63

**Comment by Top-Cat** [comment]
Fixed by beatmaps-io/beatsaver-common-mp@e58313d
Will look to update old maps after that is live
