### ISSUE TITLE
The API may have a huge (more than a few MB) uploader description

### ISSUE THREAD

**Issue by WGzeyu** [beatmaps-io/beatsaver-main#164]
Recently, the crawler I created was more prone to errors when fetching data, and then I realized that the guy had written several MB of "A" in his profile.
https://beatsaver.com/profile/4285819
https://api.beatsaver.com/search/text/0?mapper=4285819
Is there really no need to put a limit on the length?
![](https://cdn.discordapp.com/attachments/882731668589387796/1024809957285187694/unknown.png)
![](https://cdn.discordapp.com/attachments/882731668589387796/1024810013539180574/unknown.png)

**Comment by Top-Cat** [comment]
Fixed
