### ISSUE TITLE
[Improvement] Probably we should improve the searching algorithm?

### ISSUE THREAD

**Issue by MicroCBer** [beatmaps-io/beatsaver-main#165]
![image](https://user-images.githubusercontent.com/66859419/193407370-c0d4569d-7f46-4997-9723-f62b41985b43.png)
![image](https://user-images.githubusercontent.com/66859419/193407375-27fb33f0-877d-43ff-a9fb-788c80f6575e.png)
The sorting of the results doesn't seem reasonable to me. The title should be considered more and the weight of the description can be reduced. Probably the searching system should be seriously considered and redesigned again? As the current searching system couldn't give us a good searching experience.

**Comment by Top-Cat** [comment]
Not a trivial problem, I'd rather get 10 results I have to look through immediately than wait 10 seconds to filter out 2 of them.

Closing as this issue has no actionable issues, just "make the site better"
