### ISSUE TITLE
Not all Cinema-supported maps are displayed

### ISSUE THREAD

**Issue by n3tman** [beatmaps-io/beatsaver-main#17]
Current feed: https://beatsaver.com/?cinema=true&order=Latest
Alternative feed: https://bsaber.org/?sort=uploaded_desc&filter_mods=cinema

Examples of maps that don't have `cinema: true` set even though `cinema-video.json` can be found inside zip:
- https://beatsaver.com/maps/1b146
- https://beatsaver.com/maps/1afed
- https://beatsaver.com/maps/1adf7

**Comment by Top-Cat** [comment]
I assume these maps don't have cinema set as a suggestion which is the generally accepted way to indicate that a mod should be loaded. I'd argue cinema shouldn't work on those maps.

**Comment by n3tman** [comment]
I agree that it's best if Cinema is mentioned in map's `_suggestions` field and mod author [mentions](https://github.com/Kevga/BeatSaberCinema#info-for-mappers) it too:
> If you include a video config, please **add "Cinema" as a suggestion** in your map editor, same as you would do with Chroma. Don't set Cinema as a requirement though, since your map should always be playable without it.

But the reality is that it's not required to mention Cinema in this field for the mod to work. Only `cinema-video.json` is required.
All three maps above don't mention it anywhere in `Info.dat`, but the functionality still works (see video below).

I gathered IDs of all maps that include Cinema configs from both BeatSaver and bsaber.org (alternative listing).
BeatSaver returned 64 results, BSaber.org returned 136.
So more than half of all Cinema-supported maps are not recognized currently.

<details><summary>List of missing map hashes</summary>

```
ff96dcf707acaa5d8eae18fab365dfb8a3228549
194a6c5340529cd8e345d0143a4d39f1539b9714
e0d53553e6549a9afd67b4930bce41dfa84de11d
3d4777296730c5a20e0130e95d24f1613f8d5a46
df64ca6869a83d27952fd00c10cecad4d1fbd951
3be178735538a33ab8547196b61df1f0062d0bf8
a4b47d8ac4d7499a1271e17a1ac0ef57184499ea
b7faa2dd0307c7747d5c4498b89d149e744fce65
5bcda73a514061ab1ff28baef4dc7747471f8f3b
c3967b9ac8d3a5a1c856130e3739bed9158fa2c3
86220cb4f8b6d4c3a746f17352f065401d38572f
28dae56bea187b3573868198ab761da70c9fb6c2
a5876d2fdb51a935635dbfa8f97623dd38e0aad4
9b605453a94ab2e6c6a81cd80196775102638bdc
19def691f790f5c2b45a63039b4a6e289a8a002e
984e59be7d858b8334f09a043d665c80c07b3285
9e7263a214b0db893f14f619f5853e2df2307072
09970bbb0b004ae1f626446f4ec3c9acfa33b7fb
1694c0690d5b70077204a0463053070a13c456bf
ef3b7809a642985ef99dd497da47d03947c9c89e
387fdfb254b4f47bd4a2b49f936f2274341d7016
248f1e876feea8d50157834a3b6cf73bfb7d8fa0
e69388f0cc8cd27e05c1ef9e6755a10a6c7d8ae7
d40e9744a4946ef5a1d5deffbf6867f687fdc43a
d0fd0247da64a982c39db5efc2ae0294d6b440d6
6047a67bcd338348e363c4e9353da756d6387d38
43be7fd862e6ba1a3d5f257f1a60dd122ec9e804
40301fb8ad1f6cd26fa380e011b5e62b19dd1d1a
286896f0c09df1edecb396c1986cc9fff81935cc
2541953cde8966087b1d4cb52a253909a4e35005
a705d76c76c0af91ac2427a1c9f0173c1a3c8192
2abc97e5709507cd60747e0720a1aeb89141142b
01c9c991b7d5863de320ef42f2d5d6bbb789ae7a
786ba3fef3dd7d4f3d6b6157b26675792301b46b
9e95807609d43c4a0d0155dcf1fe1dc0a1172f24
c83ad6f59ed98d2772c694e3be5fc87ff5691cf0
8c8d11640d0aa3d6a60183c700f3f8425ddaa241
a6a56e3a885d890701d4c3507ec5f2c7e31184a2
044ec905d95ab775953c8e5d4cbadbb6799d958f
adde0bafab0dc2f409223206a2ad21499af0b44b
98cd0a0708cd1d2ef0f7d6d511e94d9756c4ccaa
ec428f4021208ff5d2fdc9664bbb4fddb81332b0
775ce50fabbbea493f304fa4f3ba8db4cdc41875
c4cdd2437d72efba61eec4c4681114873d5d4d4e
43f428d6c5a9865d5e8357666cc03bd73de1586f
d366ea812ee431b4b8e9244a07f07fa8c39dbc55
41b7ae527f472bef70ce8c7c040f9388e456b5ad
c43db47d20f58280be9cc3bfd4657a3cb40f1aba
37fbe2ff345ecf98e65b2eb09859215c71fe2ecd
cbcc97334fdc4a08ea858813531a2210475e2623
71964c443c08a921e850fd6c74a9aee417847b5c
4f1f3665756c2cb09048dff336e539530b45dd24
06472037c8e37adbd18e791d3bdbdc08b58e1125
66c089833ced3282e29b5eac91855b563c0ff8e9
b2a57bbcad513ac4f61392ffed4c3b2876f5d178
8233f236e15b2356cb4974f7e7a37764c7257925
ab682f32b72f3d6176def29c31615a83ff3bfbbf
90d2c06c12c16337a9bc39cc113e97240f9df47b
17a2d6a50a49b4f40b15405f8a1925b341bee14e
2b2f2057acd2f1ce305adb70553c7b9c6e3fc08b
299abd08d783e186c27f281af354cee62abcd67d
2ba431acb976bd4fb7133bcf5344909046590ee0
6e5ec1102c8253cd02464c35f32efcdf711298f7
8740743406329cc0410947178c475f3e35e2a51d
1a20ae1ecc6382625056073294b032b6dc0177dc
162f98b752c9c6e477a8a8f3ce2e0e318c622f5b
764aa5ea5a648a666e18a241dc7df996d2cf89a8
17ff091113067b3297542a2fd0acb43a3b960a89
0abb962edf456dc683ab513efd3516a69bf661b9
02866b3866b33e949c7574d5d868906a7924852e
d7e39c6b9092073fbdc3bfb03afc7ef6fc739e10
517f2756dcf50ca6f9775ab262b0d4ccdc8bd6b5
```
</details>

I don't think BeatSaver should be policing whether or not `_suggestions` field is set in this case. And I doubt all those 72 maps are gonna be reuploaded, so people will miss the opportunity to play them.

Note: I didn't include preconfigured maps in this calculation (videos added by mod author), because I don't think they belong to these results: https://github.com/Kevga/BeatSaberCinema/blob/master/Resources/bundled-configs.txt

https://user-images.githubusercontent.com/16892631/129356167-31cdcb12-e92e-4029-8a1f-a4f4588bbabb.mp4

**Comment by Kevga** [comment]
Top-Cat discussed this with me, I will disable video playback if the map is played from the WIP folder and the suggestion is not set. Maybe also display a message to remind the mapper about adding the suggestion. That should hopefully fix this issue for maps uploaded in the future.

**Comment by n3tman** [comment]
Alright, seems reasonable. I'd still display such maps at BeatSaver, but I can satisfy my needs with bsaber.org for now (to compile a playlist with best maps using Cinema mod).

If not for that website, the only way I could do it is by downloading 50k maps myself (or searching for "cinema" word in map descriptions, but it's not ideal). People spent time finding suitable videos and setting up the config, so it's kinda sad to punish them for not adding one line to `Info.dat` (which wasn't even required for the functionality to work).
