### ISSUE TITLE
Incorrect/Inaccurate map ratings

### ISSUE THREAD

**Issue by Smile249** [beatmaps-io/beatsaver-main#174]
I'm sure this has been addressed before but this still bothers me to this day that the vote ratings are really funky.

How is a 10/0 map only 75.7%? That should be a solid 100% since there are no downvotes.
<img width="459" alt="image" src="https://user-images.githubusercontent.com/85846415/208110032-a9c36409-6bac-4c58-b0fa-379b8066cb32.png">

I got a formula that should work properly except when the ratings are 0/0, but that should be fixable with some simple code like;
if (posRating && negRating == 0) { //do stuff };

Anyways, consider using 100-(100/posRating*negRating). It will make more sense to me (and prob many others).

**Comment by symphonic643** [comment]
Someone else will have to point out where the formula is in the code, but the factor of number of total votes is what is making that number what it is. Essentially, the more votes there are, the closer it is to the "actual" ratio. The formula used to be even more negatively weighted than the current iteration, I believe. You can sort of see it visually my noting how much gray space there is on the score graphic.

**Comment by Top-Cat** [comment]
Votes are a population estimate. There are only 10 votes but 1000s of players, given the small sample size our error bars are massive so we estimate that if everyone voted some would not be positive.

They are working exactly as intended.

**Comment by Smile249** [comment]
Alright, thanks for explaining.
