### ISSUE TITLE
Search by date not working as expected

### ISSUE THREAD

**Issue by TheCzar1994** [beatmaps-io/beatsaver-main#175]
Actually discovered by Syndicate but I'll report it. When narrowing search results by using the time frame selection, the preview of the song covers a majority of the previous month button.

~~Also, none of the keyboard shortcuts listed in the "?" menu worked for me.~~ This is working. I must've been doing something wrong.

<img width="332" alt="Screenshot 2022-12-22 173306" src="https://user-images.githubusercontent.com/104277242/209242665-094b3c78-ff0c-4046-9dbd-83c33d78d38a.png">

**Comment by Top-Cat** [comment]
Keyboard shortcuts work for me, some aren't applicable to range selections.
