### ISSUE TITLE
Bookmarks playlist does not update automatically

### ISSUE THREAD

**Issue by Morgolf** [beatmaps-io/beatsaver-main#181]
Hi, the bookmarks playlist on Beatsaver website seems to not update automatically, after adding maps to it with the bookmark button on the website and refreshing it in game, added maps do not show up in game.
The syncURL in the playlist seems to be correct so I suspect it may be an issue with the privacy setting of the playlist itself?

**Comment by Top-Cat** [comment]
Yup, this is an issue with whatever playlist plugin you're using. The author needs to add support for private playlists.
