### ISSUE TITLE
API Bug: maps/hash Endpoint delivers always false for bookmarked

### ISSUE THREAD

**Issue by Tatenshi** [beatmaps-io/beatsaver-main#182]
The maps/hash endpoint in the API always returns false, regardless if the song is bookedmarked or not.

maps/id works correctly.

Example:
https://beatsaver.com/api/maps/id/6304
This returns true for bookmarked while
https://beatsaver.com/api/maps/hash/dc057da39038b261b9485c38f41f66645824c4f7
returns false.

This example map also has just one version.

**Comment by Top-Cat** [comment]
Any api issues should be about requests to https://api.beatsaver.com
The /api routes are not supported externally

**Comment by Tatenshi** [comment]
Oh sorry i didnt notice, that there was an external alternative to /api.

The issue also occurs with https://api.beatsaver.com/

For this the example links are the following:
https://api.beatsaver.com/maps/id/6304
and
https://api.beatsaver.com/maps/hash/dc057da39038b261b9485c38f41f66645824c4f7

**Comment by Top-Cat** [comment]
Probably should have started there?
<img width="181" alt="Screenshot 2023-02-11 at 19 58 56" src="https://user-images.githubusercontent.com/534069/218278705-2eb0ae43-c601-4321-bf20-47649156a300.png">

I also have no idea why you would be requesting the status of a single map externally. External api authentication is in what I would maybe call a trial phase.

**Comment by Tatenshi** [comment]
I did start there. But at some point it seems I have used the wrong URL from the network-analysis tab instead of the swagger documentation. Sorry about that, should have checked beforehand!

As for the use-case, I am right now prototyping a quest-mod to bookmark and unbookmark songs from inside the game. Therefor, I request the bookmark status of the map, when the user selects this map.
If the prototype were successful, I would ask your team if you already had something like this in development and if not if I can publish it :)

**Comment by Top-Cat** [comment]
You should probably look at [BSDL](https://github.com/Top-Cat/BeatSaverDownloader), it already does this.
It loads the whole list rather than making 100s of requests as users scroll through their feed.

As I said though, this authentication is still in trial and you should probably head to discord to discuss getting that sorted.

**Comment by Top-Cat** [comment]
Removed confusing value from api in beatmaps-io/beatsaver-common-mp@3995902
