### ISSUE TITLE
beatsaver insisting I set a username when I have one already

### ISSUE THREAD

**Issue by terrarum** [beatmaps-io/beatsaver-main#183]
I signed in to beatsaver using Discord and now it keeps asking me to set a username, but my username is already set. I had a regular email/password account before but decided to sign in with Discord instead.

![image](https://user-images.githubusercontent.com/2625755/224844854-5f89e998-c89a-4103-8199-4ed42e1961f5.png)

Clicking links now redirects me to that page. I'd like to be terrarum so I'd rather not pick something else if I can't change it later as it says, but I'm guessing that logging in with two different methods has caused some kind of conflict.

**Comment by Top-Cat** [comment]
Not a bug
