### ISSUE TITLE
Incorrect Song Length on Track

### ISSUE THREAD

**Issue by KieronQuinn** [beatmaps-io/beatsaver-main#188]
Possibly related to #132 

Seems at least one track is reporting a length of around 1/3 of the length of the actual track: https://beatsaver.com/maps/76b0

Website is reporting 3:58 but the track length (as verified by the description) is 10:58

**Comment by Top-Cat** [comment]
Entirely unrelated. This is legacy data imported from the old beatsaver database that's just wrong 🤷‍♂️
Sadly there's no real way of knowing how much data is like this.

It's 10:56 not 10:58, updated the metadata
