### ISSUE TITLE
After using filters, scrolling to the bottom no longer triggers loading

### ISSUE THREAD

**Issue by WGzeyu** [beatmaps-io/beatsaver-main#19]
https://beatsaver.com/?minNps=4&order=Latest
For example, this address only uses a filter with the lowest NPS=4. As a result, there are only 13 songs left on the first page, and scrolling to the bottom will no longer trigger loading.
![](https://wgzeyu.gtxcn.com/img/bs/saver4.png)

**Comment by Top-Cat** [comment]
Ah, pages are supposed to always be 20 items. This should now be the case for these pages.
