### ISSUE TITLE
[Request] Add Difficulty Filter to Search

### ISSUE THREAD

**Issue by CyferShepard** [beatmaps-io/beatsaver-main#196]
Hi, just wondering if its possible to add a filter to only search certain difficulty maps. This would be a really good addition

**Comment by Top-Cat** [comment]
Literally right there
![image](https://github.com/beatmaps-io/beatsaver-main/assets/534069/0d328099-5c59-4656-996c-6c5e69ab998e)

**Comment by CyferShepard** [comment]
Oh thanks, sorry for that. I was looking for something along the lines of a dropdown or a checkbox where you can choose from Easy, Normal, Hard etc. is there a link to docs that tell me what this range slider means, just by looking at it im so lost? Thanks
