### ISSUE TITLE
Incorrect validation when _colorSchemes or _environmentNames is empty

### ISSUE THREAD

**Issue by XAce1337manX** [beatmaps-io/beatsaver-main#197]
If either are empty, a map with an Info.dat version of 2.1.0 is unable to be uploaded.
![image](https://github.com/beatmaps-io/beatsaver-main/assets/68104413/03d71588-7e07-4ac4-950c-ec3c92df8c96)

Official editor behaviour for maps without a color scheme have empty `_colorSchemes` and `_environmentNames` with `_beatmapColorSchemeIdx` and `_environmentNameIdx` set to 0.

**Comment by Top-Cat** [comment]
Should be fixed
