### ISSUE TITLE
Cover image is not uploaded when creating playlist

### ISSUE THREAD

**Issue by Undeceiver** [beatmaps-io/beatsaver-main#199]
Instead, it requires you creating the playlist, then editing it and adding a cover that way. Not sure since when this has been happening, but it happened to me exactly like this on 3 playlists one after the other.

**Comment by Top-Cat** [comment]
Can you create an example playlist that you have created with an image but not edited and link it here?

**Comment by Undeceiver** [comment]
https://beatsaver.com/playlists/160684

**Comment by Undeceiver** [comment]
Oh, after a couple of refreshes the image eventually appeared. That is odd.

**Comment by Undeceiver** [comment]
Yes, it seems that it takes about 20 seconds to show the image, refresh or not (including Ctrl+F5). Not as big of an issue and not sure if you want to investigate then.
