### ISSUE TITLE
Allow certain CSPs

### ISSUE THREAD

**Issue by ByteAlex** [beatmaps-io/beatsaver-main#21]
Hey there!

For my project https://github.com/AIOSaber, and specifically the BeatSaver Extension (https://github.com/AIOSaber/BeatSaver-Extension/pull/2), I'd really like if you could add the following policies:
* "connect-src localhost"
* "unsafe-inline"
* "style-src https://cdn.rawgit.com/*"

This would allow my userscript to access
a. The local client via get/post & websocket
b. & c. Load a "toast" library which is used for some simple popups.

Here's an example with disabled CSP on my local browser:
![grafik](https://user-images.githubusercontent.com/2230292/130333798-a0e0d725-5266-47b8-931a-4a2da532bb25.png)

Would it be possible to get this or could you suggest another workaround?

Thanks & Best
Alex

**Comment by ByteAlex** [comment]
After reading through beatmaps source, I figured that I cannot open a PR to support my use case, since I did not find any policy headers in the code. So I assume some proxy middleware of yours appends those headers.

**Comment by AntiLink99** [comment]
[](https://api.beatsaver.com) would be cool too for my TamperMonkey plugin: [](https://github.com/AntiLink99/beatsaver-additional-info)

**Comment by Top-Cat** [comment]
"unsafe-inline" is a no, that's 90% of possible vulns

beatsaver-additional-info looks like a complete waste. Download counts are by design not on the layout for now. I'd rather remove the field from the API for the time being.

**Comment by ByteAlex** [comment]
Okay, unsafe-inline is a no, - I can possible work around that, by including the css/scripts directly into my code, but how is it looking towards connect-src localhost? I dont see a real security vuln there, except the user actually installed malware, but then they got other issues than xss on beatsaver, I guess.
The connect-src for localhost is the only hard requirement for my project.

**Comment by Top-Cat** [comment]
I think that should actually be fine. As you say the other CSP rules would stop anything the user hasn't approved connecting anyway.

**Comment by ByteAlex** [comment]
Thank you, I already adjusted my userscript to work just fine without the external dependencies & rewrote the unsafe-inline styles into proper css statements.
Please let me know once this change was deployed. 😄

**Comment by Top-Cat** [comment]
Should be deployed now

**Comment by ByteAlex** [comment]
I see it is deployed, but I still get a CSP error when trying to connect to http/ws.
![grafik](https://user-images.githubusercontent.com/2230292/130468189-36fa5388-067b-4d43-b026-972f204fcb77.png)

What I think the issue is: different protocol & port from the actual website.
I think it actually needs specific whitelisting as in:
`connect-src 'self' *.fontawesome.com http://localhost:* ws://localhost:*;`

Reference: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/connect-src

Sorry for the trouble 🙏

**Comment by ByteAlex** [comment]
Saw the new headers, it works now. Perfect. Thank you!
