### ISSUE TITLE
Potential issues witth data on mappers-page

### ISSUE THREAD

**Issue by MrKingfisher** [beatmaps-io/beatsaver-main#228]
from time i go down the rabbit-hole just for fun and i have found maps by doing that.
however i am  a bit curious to if (a mapper deletes their map) it should update on the mappers-page aswell or if bot map in this case with image bellow gets deleted it should also update up/down votes aswell

yes yes.. its a bot user but where does itt pulls those numbers from???
![image](https://github.com/beatmaps-io/beatsaver-main/assets/7417261/9dcff266-7950-4623-ad4d-4949cb27e5a4)

**Comment by Top-Cat** [comment]
Currently those numbers are only updated when a new vote is cast.
I've added an update when a map is deleted too.
