### ISSUE TITLE
Allow switching or changing capitalization of display names

### ISSUE THREAD

**Issue by n3tman** [beatmaps-io/beatsaver-main#25]
Related to #11:
<details>
<summary>Discord Quotes</summary>

![2021-08-24_113516](https://user-images.githubusercontent.com/16892631/130585075-8392542a-29d0-49a5-be94-423455920df1.png)
![2021-08-24_113617](https://user-images.githubusercontent.com/16892631/130585083-11ade662-a8bb-4082-8631-6ce0c3aca74d.png)
</details>

I see two solutions here:
1. Allow to switch display name between: old beatsaver username / Discord name / Steam name (all linked accounts, basically)
    This, however, adds more problems: 
    - What if people change Discord/Steam names and want to see the same ones on BeatSaver? Some sort of syncing needs to be added (e.g. a button "Sync linked name")
    - Someone might change their name every day as a joke or to impersonate other people, etc. This can be circumvented by allowing to do such syncing once in X months, for example
2. Allow to change capitalization of the old beatsaver username.
    This wasn't allowed on the old website, but it certainly would be appreciated.
    
Note: API should still provide alphanumeric usernames. This task is about display names that may be added as a separate field (if it's more than just capitalization).

**Comment by Top-Cat** [comment]
There's a conversation to be had here: I think people could change their name on the old beatsaver if you submitted a request and it actually got noticed.

So, should we just allow accounts to be entirely renamed? The ids on maps would stay the same (which can't be said for the current discord linking, I'm so sorry) so it should be fine (other than bsaber) and the change may allow people to use a name that matches their bsaber account.

imo these changes should be limited, 1 per day/week/month/whatever so people don't spam changes

Thoughts from anyone welcome below :)

**Comment by Top-Cat** [comment]
I have now changed how discord linking works so maps will never change id (which was personally a blocker for this change)
