### ISSUE TITLE
clicking on a @ in a notification description

### ISSUE THREAD

**Issue by MadChase** [beatmaps-io/beatsaver-main#257]
clicking on a @ in a notification description just sends you home
![Screenshot 2023-12-06 090457](https://github.com/beatmaps-io/beatsaver-main/assets/69113929/9ca43afa-80d5-48c5-b6e4-ad8018372ebe)

**Comment by Top-Cat** [comment]
Only if it's truncated, not much to do about that. Go to the map page and click it from there.
