### ISSUE TITLE
Map stats on user profile include data from unpublished maps

### ISSUE THREAD

**Issue by namaki-mono** [beatmaps-io/beatsaver-main#27]
- The map counters include the stats of unpublished maps (maps, BPM, score, duration, difficulties)
- Subsequent difficulties added via the unpublished upload feature increment the difficulties count
- After publishing an unpublished map, the added difficulty count does not correct itself, and a users difficulty count will be bloated with "ghost" difficulties

For example, this map (https://beatsaver.com/maps/1b7fb) contains ~10 iterative versions in its unpublished state, and despite the versions being hidden from view now that it is published, they are still being considered in the user stats (https://beatsaver.com/profile/4284242). Note the mismatch of difficulty count in the user stats compared to the difficulty count in the published maps.

**Comment by Top-Cat** [comment]
Woops, was already fixing this :)
