### ISSUE TITLE
Beat Saver Review System: Comment

### ISSUE THREAD

**Issue by remecart** [beatmaps-io/beatsaver-main#273]
U+200C‌ ( ZERO WIDTH NON-JOINER ) character can be used to submit empty reviews. 

Example:
https://discord.com/channels/882730837974609940/1046500499823800390/1191430756719931613
https://beatsaver.com/maps/387e1

**Comment by Top-Cat** [comment]
Seems like a lot of effort when you could just leave an empty review with no zero width spaces?

You've overcomplicated it
