### ISSUE TITLE
[Request] Add comments

### ISSUE THREAD

**Issue by Parapass** [beatmaps-io/beatsaver-main#28]
This will allow mappers to easily gain feedback on their maps from users.

I imagine the comments would look something like modelsaber's comment system but following beatsavers's new theme.
![image](https://user-images.githubusercontent.com/59424861/131251783-2be40473-7ea3-41e2-9f1c-ea2cb6f75a8e.png)
Here's just a small mockup I made.
![image](https://user-images.githubusercontent.com/59424861/131251969-f91086eb-e5d9-4f6f-b919-4b5748aa3aa6.png)

**Comment by helencarnate** [comment]
@Top-Cat I will add bsaber roadmap items onto this issue since you already have it flagged as an enhancement. I'll be working on some mocks as I fiddle with the map detail page.

**Comment by helencarnate** [comment]
@Parapass A simplified review system to replace the one on Bsaber is on our roadmap and one of our few remaining "big" transition items. No ETA but this is planned.
