### ISSUE TITLE
CDN problem

### ISSUE THREAD

**Issue by WGzeyu** [beatmaps-io/beatsaver-main#29]
I found that some newly uploaded songs are on `as.cdn.beatsaver.com`, and the covers and maps cannot be downloaded.

And, in China, connecting to `as.cdn.beatsaver.com` almost has to go around the earth, and it is not even as good as `cdn.beatsaver.com`. Is there any optimization method? For example, add CDN address option?
I can also provide a CDN server, but the traffic is not a lot. If it is only used for Chinese users, how much traffic is required per month?

![](https://wgzeyu.gtxcn.com/img/bs/s1.png)
![](https://wgzeyu.gtxcn.com/img/bs/s2.png)
![](https://wgzeyu.gtxcn.com/img/bs/s3.png)

![](https://wgzeyu.gtxcn.com/img/bs/sp1.png)

**Comment by Top-Cat** [comment]
Latency isn't necessarily the most important metric but if you're going to provide it mtr would be more useful than ping to get an idea of what routes these are taking for you and where it's slow

If you can provide a box in china I can route Chinese traffic there but I've found very little in the region that can provide enough bandwidth. I've had users using aws in china downloading large numbers of maps who I can promise you were both using a lot of bandwidth and getting faster downloads from the asia box than the one in europe.

**Comment by Top-Cat** [comment]
fwiw, my mtr trace to your server from the box in asia:

```
Start: 2021-08-31T16:47:02+0800
HOST: as.cdn.beatsaver.com        Loss%   Snt   Last   Avg  Best  Wrst StDev
  1.|-- ip-103-164-54-12.static.c  0.0%    10    0.6   0.9   0.2   3.9   1.1
  2.|-- v607.core1.sin1.he.net     0.0%    10   35.0   5.9   0.6  35.0  10.5
  3.|-- 100ge14-2.core1.hkg1.he.n  0.0%    10   39.5  40.6  34.3  49.3   4.6
  4.|-- 132203.hkg.equinix.com     0.0%    10   36.2  39.5  35.5  48.1   4.7
  5.|-- ???                       100.0    10    0.0   0.0   0.0   0.0   0.0
  6.|-- ???                       100.0    10    0.0   0.0   0.0   0.0   0.0
  7.|-- ???                       100.0    10    0.0   0.0   0.0   0.0   0.0
  8.|-- 9.56.249.25               80.0%    10   57.4  47.2  37.0  57.4  14.4
  9.|-- 101.32.77.189              0.0%    10   39.6  41.1  36.1  52.8   6.1
```

That's a _lot_ less than the 350ms plus above 🤷‍♂️

**Comment by WGzeyu** [comment]
The above test result is to use a server in Mainland China instead of China Hong Kong.
You can try 0-cncu.gtxcn.com and 0-cnal.gtxcn.com

**Comment by WGzeyu** [comment]
```

NAS-OMV (192.168.1.152) -> as.cdn.beatsaver.com                              2021-08-31T16:52:02+0800
Keys:  Help   Display mode   Restart statistics   Order of fields   quit
                                                             Packets               Pings
 Host                                                      Loss%   Snt   Last   Avg  Best  Wrst StDev
 1. _gateway                                                0.0%   190    0.5   0.4   0.3   1.7   0.2
 2. 120.0.52.1                                              0.0%   190    2.2   2.1   1.4   7.7   0.8
 3. 221.192.1.149                                           0.5%   190    2.6   4.2   1.6  50.6   5.6
 4. 61.182.181.237                                         67.7%   190    7.3   7.9   7.2  12.5   0.8
 5. 219.158.115.77                                         97.9%   190   42.5  42.7  42.2  44.1   0.9
 6. 219.158.97.2                                           19.5%   190   46.2  48.6  42.3 133.6  11.0
 7. 219.158.24.138                                          0.0%   189   51.3  50.9  46.9  56.2   2.0
 8. 219.158.102.158                                         0.0%   189  199.9 202.7 199.8 229.7   3.5
 9. 100ge12-2.core1.lax2.he.net                             0.0%   189  171.7 173.2 171.6 196.7   3.8
10. port-channel3.core3.lax2.he.net                         0.0%   189  170.9 171.6 170.8 179.3   1.0
11. 100ge10-1.core1.hkg1.he.net                             0.0%   189  316.5 316.7 315.9 320.1   0.7
12. 100ge2-1.core1.sin1.he.net                              0.0%   189  348.4 352.1 348.1 371.5   7.7
13. contabo-asia-private-limited.e0-7.switch2.sin2.he.net   0.0%   189  340.4 341.1 340.1 390.3   3.7
14. as.cdn.beatsaver.com                                    8.5%   189  362.0 352.7 338.5 369.6   4.8

NAS-OMV (192.168.1.152) -> cdn.beatsaver.com                                   2021-08-31T16:54:08+0800
Keys:  Help   Display mode   Restart statistics   Order of fields   quit
                                                               Packets               Pings
 Host                                                        Loss%   Snt   Last   Avg  Best  Wrst StDev
 1. _gateway                                                  5.4%    74    0.6   0.6   0.3   5.6   0.7
 2. 120.0.52.1                                                0.0%    74    1.6   2.6   1.4  40.8   4.6
 3. 221.192.14.213                                            6.8%    74    2.0   2.1   1.5   5.4   0.7
 4. 61.182.182.145                                            0.0%    74    9.7  10.0   8.4  13.8   1.0
 5. 219.158.105.85                                           94.5%    74   37.3  38.6  37.3  40.2   1.2
 6. 219.158.103.218                                           0.0%    74   38.5  40.2  35.9  64.9   3.8
 7. 219.158.103.30                                            0.0%    74   48.4  46.5  41.8  54.2   2.4
 8. 219.158.20.162                                            0.0%    73  194.0 194.2 193.2 200.5   1.2
 9. 219.158.41.98                                            38.4%    73  201.4 202.7 200.9 224.2   4.2
10. ffm-bb2-link.ip.twelve99.net                              0.0%    73  215.7 216.0 215.3 218.4   0.5
11. s-bb2-link.ip.twelve99.net                               81.9%    73  222.9 223.6 222.5 227.6   1.4
12. hls-b3-link.ip.twelve99.net                              20.5%    73  195.5 195.5 194.7 198.2   0.7
13. hetzner-svc076536-ic365572.ip.twelve99-cust.net           0.0%    73  223.2 224.5 223.0 241.5   3.3
14. core32.hel1.hetzner.com                                   0.0%    73  194.2 196.0 193.5 206.0   3.4
15. ex9k2.dc3.hel1.hetzner.com                                0.0%    73  183.7 184.6 183.5 202.7   2.7
16. beatsaver.com                                             0.0%    73  195.5 196.1 195.5 198.0   0.4

```

**Comment by Top-Cat** [comment]
So for some reason it's going via tokyo to america before turning around back to asia

**Comment by WGzeyu** [comment]
> So for some reason it's going via tokyo to america before turning around back to asia

According to my test, China Unicom and China Telecom both use this route, while China Mobile first reaches Europe through the United States, and then connects to Asia.

**Comment by Top-Cat** [comment]
Seems like these may actually be best routed to an American server then

**Comment by Top-Cat** [comment]
Seems like from the US the biggest latency is actually added inside china:

```
  1.|-- 198.204.243.153            0.0%    10    0.3   0.5   0.3   1.5   0.4
  2.|-- 100ge15-1.edge-a.clay.mci  0.0%    10    1.2   0.7   0.5   1.7   0.4
  3.|-- 100ge0-30.edge-1.clay.mci  0.0%    10    0.6   0.7   0.4   2.6   0.7
  4.|-- 100ge0-25.edge-2.grand.mc  0.0%    10    1.1  10.1   0.5  53.7  17.8
  5.|-- 219.158.38.137             0.0%    10   42.2  39.6  35.9  43.0   2.6
  6.|-- 219.158.96.37              0.0%    10  182.8 180.7 177.5 184.6   2.4
  7.|-- 219.158.16.65              0.0%    10  203.2 206.3 202.2 212.1   3.1
  8.|-- 219.158.5.149             50.0%    10  179.6 179.7 179.3 180.4   0.4
  9.|-- ???                       100.0    10    0.0   0.0   0.0   0.0   0.0
 10.|-- 61.182.183.138             0.0%    10  191.2 191.9 190.9 195.4   1.7
 11.|-- 221.192.1.150              0.0%    10  191.6 193.3 191.5 198.9   2.6
 12.|-- 120.0.52.74                0.0%    10  193.7 194.5 193.7 197.2   1.0
```
Both 5 and 6 are registered in china.

**Comment by WGzeyu** [comment]
> Seems like from the US the biggest latency is actually added inside china:
> 
> ```
>   1.|-- 198.204.243.153            0.0%    10    0.3   0.5   0.3   1.5   0.4
>   2.|-- 100ge15-1.edge-a.clay.mci  0.0%    10    1.2   0.7   0.5   1.7   0.4
>   3.|-- 100ge0-30.edge-1.clay.mci  0.0%    10    0.6   0.7   0.4   2.6   0.7
>   4.|-- 100ge0-25.edge-2.grand.mc  0.0%    10    1.1  10.1   0.5  53.7  17.8
>   5.|-- 219.158.38.137             0.0%    10   42.2  39.6  35.9  43.0   2.6
>   6.|-- 219.158.96.37              0.0%    10  182.8 180.7 177.5 184.6   2.4
>   7.|-- 219.158.16.65              0.0%    10  203.2 206.3 202.2 212.1   3.1
>   8.|-- 219.158.5.149             50.0%    10  179.6 179.7 179.3 180.4   0.4
>   9.|-- ???                       100.0    10    0.0   0.0   0.0   0.0   0.0
>  10.|-- 61.182.183.138             0.0%    10  191.2 191.9 190.9 195.4   1.7
>  11.|-- 221.192.1.150              0.0%    10  191.6 193.3 191.5 198.9   2.6
>  12.|-- 120.0.52.74                0.0%    10  193.7 194.5 193.7 197.2   1.0
> ```
> 
> Both 5 and 6 are registered in china.

5 is in the US
[https://www.ipip.net/ip.html](https://www.ipip.net/ip.html)

**Comment by Top-Cat** [comment]
That seems like the best option for china for now

**Comment by WGzeyu** [comment]
really. I am testing with my friend's China Telecom ( `zhm233.top` )

**Comment by Top-Cat** [comment]
What do you mean, really?

**Comment by WGzeyu** [comment]
> What do you mean, really?

It seems that using a US CDN is better than the current one in Asia

**Comment by Top-Cat** [comment]
China should be routing to the us box now

**Comment by WGzeyu** [comment]
![](https://wgzeyu.gtxcn.com/img/bs/sppppp.png)

**Comment by Top-Cat** [comment]
Incredible that most hops is shortest route 🤦‍♂️

**Comment by WGzeyu** [comment]
> China should be routing to the US box now

The test is effective, let me observe the recent feedback

**Comment by WGzeyu** [comment]
It seems that because of China's speed-up and fee-reduction policy, the price of the user side has been reduced, so the network bandwidth on the server side is very expensive.

**Comment by WGzeyu** [comment]
After roughly testing, the speeds of China Unicom and China Mobile are both good, except for China Telecom...
China Telecom: 
![](https://wgzeyu.gtxcn.com/img/bs/sct.png)
