### ISSUE TITLE
Statistics / PFP Glitch

### ISSUE THREAD

**Issue by PH0ENIX-5** [beatmaps-io/beatsaver-main#30]
By clicking on "my profile" and selecting "profile" , it takes you to your maps and stuff, where for some reason the PFP and statistics bar and playlist download are missing (see image 1)

However, if you go to the leaderboards and find yourself in there and click on that, it properly displays everything like it should (see image 2)

![image](https://user-images.githubusercontent.com/89998594/131891194-d8fc1d02-580f-4566-9e2f-e3f34ce717ca.png)
![image](https://user-images.githubusercontent.com/89998594/131891605-26d770a8-02ff-4434-bccb-0ab485126083.png)

**Comment by Top-Cat** [comment]
Can you check if there are any errors in the network tab or console in chrome when your profile doesn't load?
![image](https://user-images.githubusercontent.com/534069/131924228-59f38a0d-13a9-41b5-89d7-eaaa0c113e00.png)

**Comment by helencarnate** [comment]
I can replicate the issue and don't have any errors in network and the same message in console in Chrome. AFAIK it's always been like that, even pre-transition. I just assumed it was a personal profile vs. public profile thing.

**Comment by Top-Cat** [comment]
Seems to have been an issue with the etag telling the browser the file hadn't changed when it had. This should now clear itself automatically when your browser next tries to download the js (within an hour) or you can clear your cache.
