### ISSUE TITLE
Bug: Funky OAuth2 Application management UI

### ISSUE THREAD

**Issue by TimothyGillespie** [beatmaps-io/beatsaver-main#312]
There seem to be two bugs on the https://beatsaver.com/profile#account page regarding the OAuth Sessions on under "Authorised Sessions".

Bug 1 (Singular Revocation):

Actual Behavior / Reproduction:
1. Have a lot of OAuth2 Applications
2. Try to the delete them all one by one
3. Observe that some buttons of non-revoked applications became deactivated

Expected Behavior: They don't get deactivated.

Bug 2 (Revoke All):

Actual Behvior:

1. Have at least one OAuth application in the list
2. Click the "Revoke All" Button
3. Confirm to log out as a consequence of the revocation.
4. Observe that you are still logged in and all OAuth applications are not in the list anymore
5. Reload the page
6. Observe that you are still logged in and that the OAuth applications are back

Expected Behavior: Actually get logged out (due to the warning) and actually remove all OAuth2 keys.

**Comment by Top-Cat** [comment]
I think the intention of Revoke All was to log out user devices not connected applications.
Maybe a second button is needed?

For now I've just stopped it clearing out the list so it's consistent.
