### ISSUE TITLE
Add ability to stop getting collab notifications or define the type

### ISSUE THREAD

**Issue by TheCzar1994** [beatmaps-io/beatsaver-main#336]
Currently there is no toggle to stop getting collab notifications. This means if someone you follow lit a map for a mapper you don’t particularly have an interest in, you get notified anyways. In theory, it would be nice to specify what type of collaboration took place and follow that type, however, I think that’s likely much easier said than done. In the interim, I would rather get no collab notifications over all collab notifications but I might be an outsider on that.
Edit: This doesn’t solve my actual issue when considering that I might want to be notified if lighting was done for a mapper I *do* enjoy. I’m not sure how this would be addressed.

**Comment by Top-Cat** [comment]
I think this is fixed by the recent PR. Not released quite yet though.
