### ISSUE TITLE
Possible code injection using the name

### ISSUE THREAD

**Issue by Elecast2** [beatmaps-io/beatsaver-main#34]
![image](https://user-images.githubusercontent.com/23460760/132997255-066dbfb6-624e-47ba-99a6-3ee9d40b0a3d.png)
![image](https://user-images.githubusercontent.com/23460760/132997263-b6c19888-3e03-4c3d-8956-618c003b026e.png)
Windows 10, using Google Chrome. The name is invisible in beatsaver, but you can see it is "<blank>" in scoresaber

**Comment by Top-Cat** [comment]
That player's name is just blank
![image](https://user-images.githubusercontent.com/534069/132997407-2a6e6f32-b671-4d69-b481-251450239114.png)
