### ISSUE TITLE
Add custom diff names to API

### ISSUE THREAD

**Issue by zivoy** [beatmaps-io/beatsaver-main#35]
Add custom diff names to MapDifficulty in the API response for a map

**Comment by Top-Cat** [comment]
1. Why?
2. What if I don't have the data?

**Comment by zivoy** [comment]
1. I want to display the diff names in my app if there is a custom one, instead of just saying "Expert"
   1.2. the custom diff names can also be displayed on beatsaver since people might be more used to the custom names rather than which diff it is
2. Are you not already parsing some data from the map file to get info on the difficultys in a map?

**Comment by Top-Cat** [comment]
1. Displaying custom names on the site has its own issues as there's not much more space than fits the default values to display them in so for now it's not something I want to pursue.

2. Just because I'm parsing _some_ data does not mean it's trivial to add extra fields.

**Comment by zivoy** [comment]
1. what if it shows the custom name only when you hover over it. since there are some ridiculously long ones
2. hm

**Comment by InnocentThief** [comment]
Would be nice to have that info on the MapDifficulty in the API response. I would like to show that too in my Custom Songs Manager. Beat Saber itself shows the "_difficultyLabel" if available.
As people also use the Custom Songs Manager as source to request songs it would be nice to have the same labels as in Beat Saber.
Ex. Map 1ffbf
info.dat: Easy ("_difficultyLabel": "Die Sünde lockt")
