### ISSUE TITLE
[Request] Add voting to browswer site

### ISSUE THREAD

**Issue by aceofalmonds** [beatmaps-io/beatsaver-main#36]
Quest users currently can't vote due to their particular API. Allow users to thumbs up/down songs on the browser site.

**Comment by bloodcloak** [comment]
The current system has some integrity by requiring people to own the game. Website voting will likely not be added as it can be abused from mass creation of bot accounts.

I'm pretty sure a way to vote via Quest is being worked on already as PC Oculus was added relatively recently.

**Comment by Top-Cat** [comment]
Quest users could vote using the current api if it didn't get broken when modding the game. (Like leaderboards and multi also do).
Other options are being looked at but website voting won't be the answer.
