### ISSUE TITLE
Rate limit response is missing CORS headers

### ISSUE THREAD

**Issue by TimothyGillespie** [beatmaps-io/beatsaver-main#387]
When hitting the rate limit the response does not contain CORS headers. Thus it cannot be handled in client-side JavaScript by checking the status code.

**Comment by Top-Cat** [comment]
The problem is we don't allow CORS for every endpoint and if nginx applies a rate limit to the request it can't know if the backend _would_ have sent a header.

**Comment by Top-Cat** [comment]
I guess I could look at moving the rate limiting into the application?
https://ktor.io/docs/server-rate-limit.html 🤔

**Comment by Top-Cat** [comment]
Told nginx to return `Access-Control-Allow-Origin: *` with all 429 responses on https://api.beatsaver.com
Doesn't actually need to be correct for the endpoint, you'll get the correct headers when you slow down.
