### ISSUE TITLE
AudioData.dat file removed from v4 maps

### ISSUE THREAD

**Issue by SkylerWallace** [beatmaps-io/beatsaver-main#408]
BeatSaver strips out the AudioData.dat file from v4 maps which causes the map to not work.

Happens to the following map:
https://beatsaver.com/maps/40a54

Attached a zip of the map pre-upload which loads on 1.37.4 without issue.
[Iris.zip](https://github.com/user-attachments/files/17266222/Iris.zip)

**Comment by Top-Cat** [comment]
Should be fixed. You'll need to reupload but AudioData.dat won't affect the hash (should it, I don't know?) so you'll need to make some other small change as usual.
