### ISSUE TITLE
If a user clicks "Change username" without changing the username value, the request will still go through and put the username change on cooldown

### ISSUE THREAD

**Issue by namaki-mono** [beatmaps-io/beatsaver-main#41]
When clicking on "Change username" in the user profile's "Account" section (https://beatsaver.com/profile#account) when the username field is unchanged/untouched (i.e. not dirty, still exactly the same as the user's current account name), the request will go through successfully and put the username change on the 24-hour cooldown. 

Based on the code here: 
https://github.com/beatmaps-io/beatsaver-main/blob/66cd4e0c8a552709f6879be9306232a295a47410/src/jvmMain/kotlin/io/beatmaps/api/users.kt#L168
Clicking "Change username" with the same name should return the error "Username already taken", but the same username is being caught as a unique username.

Error received after clicking on "Change username" twice:
![image](https://user-images.githubusercontent.com/81204441/134320725-d7636db7-f90f-4783-aa3d-bdf64c2ce47c.png)

**Comment by Top-Cat** [comment]
Thank you Mr Sloth, there's a new message on the client side and if you somehow bypass that it shouldn't count as a reset if your name doesn't change
