### ISSUE TITLE
can't create an account/no confirmation email

### ISSUE THREAD

**Issue by lionxturtle** [beatmaps-io/beatsaver-main#411]
I tried to make an account and it said it sent me an email to verify my account but I didn't receive it, and there's no option to resend it for some reason. Tried resetting the password and still got nothing. It only works if you login with discord, and you can even change the username, which I wish I would've known before making an account with the username I wanted, because now I can't have it since I already used it on the account that now doesn't exist.

**Comment by Top-Cat** [comment]
This is not the place for site support. You clearly have a discord account and you can get support there.

**Comment by lionxturtle** [comment]
> This is not the place for site support. You clearly have a discord account and you can get support there.

my bad, I honestly wasn't entirely sure where to put this issue in the first place. I just thought not being able to make an account like that would be considered a bug
