### ISSUE TITLE
Split mapper and uploader into different fields on the map page

### ISSUE THREAD

**Issue by stillinkansas** [beatmaps-io/beatsaver-main#42]
As it stands right now, a long mapper name + long uploader name can cause information to get cut off in the mapper field
![image](https://user-images.githubusercontent.com/85142964/134820629-c85d6f1e-1207-4555-925e-f012221fc248.png)

I would argue that these two fields could be split up into uploader and mapper.

At the very least, having a hover bubble that shows the full text would be nice.

**Comment by Top-Cat** [comment]
They used to be separate fields but they contain the same text 90% of the time. It makes no sense to dedicate space for this.

**Comment by stillinkansas** [comment]
That's fair, but this piece is still valid imo
"...having a hover bubble that shows the full text would be nice."
