### ISSUE TITLE
Apparent Issue with Collaborators

### ISSUE THREAD

**Issue by TimothyGillespie** [beatmaps-io/beatsaver-main#425]
# Actual Behavior

On the following map Bellus is displayed as collaborator: https://beatsaver.com/maps/41873
However, when looking at her profile the map does not appear: https://beatsaver.com/profile/145971
Jonas, another Collaborator, does get the map displayed on his porfile: https://beatsaver.com/profile/120215

# Expected Behavior

Either:

A) Bellus is not listed as collaborator and it is not displayed on her profile
B) Bellus is listed as collaborator and it shows up on her profile

**Comment by Top-Cat** [comment]
This is a problem with search indexing that's already fixed :)
