### ISSUE TITLE
Add a data point to the site where you can include other mappers' accounts as collaborators

### ISSUE THREAD

**Issue by stillinkansas** [beatmaps-io/beatsaver-main#43]
Having a way to specify collaborators by account would be pretty nice.

If I work on a map with someone and they upload it to their account, having that map show up on my map list too even though I didn't upload it would be cool.

If this were to be a feature, I think you would need to add another field to the map cards in the search list that differentiates between uploaders and collaborators/mappers or at least specifies the uploader field.

**Comment by helencarnate** [comment]
> Having a way to specify collaborators by account would be pretty nice.
This is handled on Bsaber by manually adding multiple mapper tags. Might be worth discussing a coordinated way to manage as part of our overall community site conversation (that I still need to schedule)

**Comment by 3Stans** [comment]
Here are my thoughts on how this could work (pasted from my closed request) ;


_**How would this work?**_ 
My idea of this would be that after a couple, or a group of mappers have finished collaborating on a map, they can decide who gets to upload it, and the person who gets to upload will be the host of the map who can then invite the other participants and allow them to link the map on their account. The linked map would appear the same as the host map and any other map on the participants account but with any votes going to the host map. 

It could be used to promote maps as well but this is not what I intend the purpose of the feature to be.

The feature could also possibly add an extra little box in the map page with a list of collaborators which are clickable and take you to the pages of each mapper.

_**Okay.... How will it work on the participant's page?**_
The host will have the main controls of the map with just a few extra buttons. If members of the collab wish to have the map on their page, then they do the following:

1. Click an addition "Invite Participant" button (or something along that line)
2. Search for participant mapper name
3. Invite

On the participants side, they have it a little easier and just have to check their alerts tab for an invite. If they have an invite then they have an option to accept or decline, if they choose to accept then the map will appear as the latest upload on their profile but will not re-post to the latest feed on BeatSaver. 

### - What about moderation of this feature?**

- Well first off, participants have the option to accept and decline the invite, declining the invite will simply clear the notif from the alerts tab and the map will show on their account.
- Participants will also have no control over the map on their account, they cannot edit, unpublish, republish, or delete the map from 
BeatSaver, they can only remove the linked map from _their_ account.
- People can also not request to be invited to reduce spam of some kid who wants to try and pass off as helping with the creation of their favorite mod map Up and Down.
- Map hosts can also choose to revoke map linkage by going to the participants page with the linked map and clicking a newly added button labeled "Unlink Map"
- This is separate but their could also be an option for mappers to block other mappers from allowing them to send invites to them.
- As well as a toggle to simply not accept invites. 
- I don't really think these two would be needed but well sometimes the community gets a little crazy.
- Oh and AI made maps that have been deemed certainly made by an AI would not be allowed to be linked.

### - some neat example pictures:
![beatsaver request1](https://user-images.githubusercontent.com/74908347/158039466-da8d60ef-01cf-4de4-bdd2-c96239399b1a.png)

![image](https://user-images.githubusercontent.com/74908347/158039505-57cd5cb0-a1b0-45ac-83b6-460cf0a9b893.png)

**Comment by Jeyd06** [comment]
Hi everyone,
It will be amazing to have this point to support every mappers who works also in collab
And it would also allow us to be sure to have played on all the maps of our favorite mappers by doing a search
Thanks a lot 😉

**Comment by soliwoli** [comment]
is this still going?

**Comment by Top-Cat** [comment]
Completed
