### ISSUE TITLE
[BUG?] API Behavior of `&after=` in Latest

### ISSUE THREAD

**Issue by Zingabopp** [beatmaps-io/beatsaver-main#44]
The `&before` parameter in `maps/latest` API endpoint does not include the beatmap posted at the exact time specified in `&before` (expected). However, the `&after` parameter does include it. If a client is paging forward and back using the first and last beatmaps' upload date you end up with a repeated beatmap when moving towards the latest uploads unless you add a millisecond to the upload date on the first result.

**Comment by Top-Cat** [comment]
This is actually not the case, it's non-inclusive in both cases.
The actual problem is a precision error where the number of decimal places stored in the database is greater than that the API uses making it appear that way.

**Comment by Top-Cat** [comment]
In fact the API gives all the precision, looks like this is actually a C# problem?

**Comment by Zingabopp** [comment]
It might be, this is the DateTime format I'm using to convert `yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fff'Z'`

**Comment by Top-Cat** [comment]
The API is giving values to 6 decimals though: eg `"createdAt": "2021-09-27T14:30:04.234334Z",`

**Comment by Zingabopp** [comment]
That did indeed fix it, thank you.
