### ISSUE TITLE
Map upload not supporting v4 data setup

### ISSUE THREAD

**Issue by Poochylord** [beatmaps-io/beatsaver-main#444]
When trying to upload any map made within the BS v4 editor (1.34.5+), the uploader prevents submission due to "spawnRotations" being absent. According to the BSMG wiki this structure was deprecated and replaced with a "new object-level syntax" in v4 for assinging, well, spawn rotations. Is there any workaround for this issue at the moment and if so, what?

![image](https://github.com/user-attachments/assets/52899643-c929-44fa-b555-727728b483cf)

**Comment by Top-Cat** [comment]
Can you attach your map or an example from the editor?

**Comment by Poochylord** [comment]
Oh right, here you go ^^ this map is made entirely in v4, in case that's important
[Lafuitedesjours.zip](https://github.com/user-attachments/files/17832333/Lafuitedesjours.zip)
