### ISSUE TITLE
Negative filters?

### ISSUE THREAD

**Issue by NullVoxPopuli** [beatmaps-io/beatsaver-main#456]
Similar to: https://github.com/beatmaps-io/beatsaver-main/issues/105

I'd like to be able to remove things from search results.
For example, say someone never wants a nightcore remix (or remixes entirely), they could `-nightcore` (or `-remix`) in the search (or maybe there is a `<details>` for negative filters entirely so the same UI can be re-used.

This would help me be a lot less overwhelmed when looking at what's been uploaded in the last month or two, as I can filter out types of music that I don't care about.

thanks!

**Comment by Top-Cat** [comment]
If you want to avoid nightcore you can already do that (alt+click)
<img width="676" alt="Screenshot 2024-11-24 at 16 13 20" src="https://github.com/user-attachments/assets/43bd4ac1-21b9-4667-aafe-0a2ee8b9c430">

**Comment by NullVoxPopuli** [comment]
Does that only work on tags? (and correctly tagged uploads?)
or does it also apply to the text/title?

**Comment by Top-Cat** [comment]
Does alt+clicking work on the text/title? Why would it?

**Comment by NullVoxPopuli** [comment]
looks like you can only do `-` once -- alt-clicking replaces the current negated tag, rather that adds another

**Comment by Top-Cat** [comment]
Shift

**Comment by NullVoxPopuli** [comment]
doh thank you!
