### ISSUE TITLE
Ratio column on mapper list drops leading zeros in the decimal

### ISSUE THREAD

**Issue by stillinkansas** [beatmaps-io/beatsaver-main#46]
![beatsaver percentage issue](https://user-images.githubusercontent.com/85142964/135911449-404ecafa-47af-45de-adee-293fc0ba9f76.png)

This number should be 77.05%. I noticed this by chance because my account also should have a leading 0 in the decimal, but it doesn't.

**Comment by Top-Cat** [comment]
Fixed by beatmaps-io/beatsaver-common-mp@b839484fb13afc6641cf1463d87401c370c1c160
Will be live soon:tm:
