### ISSUE TITLE
V3 Converted Collider map not submitting to beatsaver

### ISSUE THREAD

**Issue by GoldGamer207** [beatmaps-io/beatsaver-main#462]
so i used the collider env to light a map, then used the v4 to v3 converter in the bsmg discord in order to make it work in chromapper, but when i tried to re submit it it gave me an error saying that it wasn't a supported environment (see attached image). I believe that when you added v4, you didn't account for converted v4 maps. it should be an easy enough fix, just add the environment names of newer maps to v3 formatted maps as well, so people are able to submit things on v4 environments in v3 format (I.E. v4 lightshows using chromapper and/or noodle extensions)
![image](https://github.com/user-attachments/assets/7a189180-22ce-41a5-b109-ce328c752557)

**Comment by Top-Cat** [comment]
Please attach your map

**Comment by GoldGamer207** [comment]
[Beta Snow.zip](https://github.com/user-attachments/files/17909449/Beta.Snow.zip)
