### ISSUE TITLE
Song name research issue with special characters.

### ISSUE THREAD

**Issue by Kuurama** [beatmaps-io/beatsaver-main#55]
You can't research maps containing special characters like : https://beatsaver.com/maps/13757 => "FLügeL" while you could simply search => "Flugel" (which doesn't show anything right now).

An other "issue" might be with mutiple string research.
=> If you search "touch touch" you won't ever find the map named "touch touch" but only a lot of maps containing "touch" in their name or even description (I don't know why your research is based on description tho), I know you can bypass the search by multiple string with "", but yes.

**Comment by Qwasyx** [comment]
In a similar way there are some maps that are just fully impossible to find, for example a lot of the maps of the song KING like https://beatsaver.com/maps/17195 even though it seems like it should have a pretty high relevance given its 92% rating.

**Comment by Top-Cat** [comment]
?
<img width="578" alt="Screenshot 2021-11-11 at 22 51 42" src="https://user-images.githubusercontent.com/534069/141380346-44b1a352-eb32-4188-8d1b-14cdb0218d97.png">

As for touch touch, that's just how search works, you can't optimise for every use case as you said there's a simple workaround.

And king, it does come up rating just isn't relevance. Lots of map names and descriptions include the word king.
<img width="1142" alt="Screenshot 2021-11-11 at 22 54 50" src="https://user-images.githubusercontent.com/534069/141380594-3421ff0d-71ff-4183-8dc4-dbc50b2e3223.png">

**Comment by Kuurama** [comment]
No i meant it's impossible to find the map with what everyone will type : "flugel" without the special character. or even "arpeggyo".
Using InvariantCultureIgnoreCase for exemple could fix it.
![image](https://user-images.githubusercontent.com/74458092/141381113-223a58f0-57f3-4030-924d-70f1c499919d.png)
