### ISSUE TITLE
When going to the BeatSaver website via http:// or lack of prefix, the website redirects to the home page

### ISSUE THREAD

**Issue by namaki-mono** [beatmaps-io/beatsaver-main#56]
When going to BeatSaver via http://beatsaver.com/profile/4284242 (note the http) or **beatsaver.com/profile/4284242** / www.beatsaver.com/profile/4284242 (note the lack of prefix), the website redirects the user to the https home page rather than the https version of the provided URL.

This is an issue for those who, for example, put their BeatSaver profile in their Twitter profile, and to try and save character count, remove the initial protocol. When clicking on the link, it leads to the home page instead of their profile page. Consider the URL in this user's Twitter profile: https://twitter.com/Daisuki_Salami

Other websites handle the above situation as expected, redirecting to the correct https version of the website. For example, http://www.youtube.com/watch?v=dQw4w9WgXcQ and **youtube.com/watch?v=dQw4w9WgXcQ** / www.youtube.com/watch?v=dQw4w9WgXcQ both redirect as expected to https://www.youtube.com/watch?v=dQw4w9WgXcQ .

This issue occurs on Firefox 94.0.1, and partially functions correctly on Chrome 96.0.4664.45. On Chrome, having no prefix automatically appends the https:// to the beginning of the URL if none is provided, but going to http://beatsaver.com/profile/4284242 has the same issue as Firefox.

**Comment by Top-Cat** [comment]
Not sure what you mean by "functions correctly on Chrome 96.0.4664.45" this behaviour is not browser related. Maybe you have a chrome plugin like https everywhere?

The behaviour is intended to prevent people from making api requests against non-ssl endpoints without realising and sending data in the clear.

I have however just enabled HSTS which will mean that anyone who has previously visited the site will automatically make their request as HTTPS. Which means if you try now it will probably work for you but I'd still recommend including the protocol as it won't work for everyone.

**Comment by Top-Cat** [comment]
Follow-up: I've also submitted the domain to the HSTS preload list which when accepted should mean most users will use HTTPS regardless
