### ISSUE TITLE
I want to publish the Songmap of Unpublish to a limited number of people.

### ISSUE THREAD

**Issue by denpadokei** [beatmaps-io/beatsaver-main#59]
Until a while ago, the Unpublish Songmap was also able to get details via the API.

This made it possible to have a test play with SongRequestManager, etc. However, since some time ago, if the map status is not Publish, a 404 is returned.

Let me get the details only if you specify the "id" directly in the API.

**Comment by Top-Cat** [comment]
The site is not your personal dropbox. At least for now this is intended.
