### ISSUE TITLE
Implementing playlist importing from a bplist?

### ISSUE THREAD

**Issue by bloodcloak** [beatmaps-io/beatsaver-main#63]
As an alternative method to creating a playlist on the site

**Comment by helencarnate** [comment]
@bloodcloak Are you aware of a mod feature related to "highlighted difficulties" in playlists? Pixelboom raised this in conversation about the switch to using "Curated" playlists in-game vs. Featured from the Bsaber "API" and it wasn't a thing I'd heard of before. He asked if retaining highlighted difficulties could be a thing for any future imported bplists.

**Comment by helencarnate** [comment]
*seconding this need after working on the giant beasties playlists*. Ideally one could just paste a bunch of comma-separated map keys into a field on the playlist creation screen and POOF, playlist. I suspect that would cut out the middle-man of Blood's NoodleLister utility (though doesn't answer the question about highlighted difficulties)

**Comment by bloodcloak** [comment]
Still probably want a bplist import as the core option for those that want to build lists elsewhere (ex. in-game) and not have to mess around with typing out keys

**Comment by stillinkansas** [comment]
As Helen mentioned, this would be super helpful for some planned curator process and community event improvements
- Update nominee playlists for each category for beasties
- Update new/open queue playlists for curation request work
- Update curator picks monthly map pack
- Update curator picks yearly map pack

**Comment by Top-Cat** [comment]
Pretty sure this is done and I forgot to close this.
