### ISSUE TITLE
Map Does Not Populate Leaderboard

### ISSUE THREAD

**Issue by stillinkansas** [beatmaps-io/beatsaver-main#68]
https://beatsaver.com/maps/1fcf1

This map seems to be broken in some way. The only things I noticed other than the leaderboard missing on beatsaver is that the mapper name is missing and the difficult is E+ in beatsaver, but Expert in scoresaber.

The leaderboard shows up in scoresaber.

**Comment by Top-Cat** [comment]
The map is broken not the site
