### ISSUE TITLE
[Request] See downloads, up/downvotes, key on map card

### ISSUE THREAD

**Issue by helencarnate** [beatmaps-io/beatsaver-main#7]
Request by users to replicate OBS (Old Beat Saver) functionality to see download count, total upvotes, total downvotes, and the map key on the map card in search results in addition to being available on the map detail page.

**Dependencies:** Data merge- on votes/downloads

LMK if you'd like me to mock some options since I have this template built in XD

**Comment by helencarnate** [comment]
![image](https://user-images.githubusercontent.com/57695406/128621401-02dc79d7-d27f-4a45-b360-086bc3730658.png)
This possible wireframe also covers Issue #13. Current state on the bottom, Mock on top.

**Comment by helencarnate** [comment]
Another possible wireframe with compromise diff label: 
![image](https://user-images.githubusercontent.com/57695406/128789806-9ae3ee74-17f2-4b10-a8ac-3e2b21d05be2.png)

**Comment by Top-Cat** [comment]
Up/down votes are technically visible by hovering over the percentage (the bar arguably gives you an easier point of comparison between maps anyway if you understand how to read it) and the key has been added visibly on the right.
