### ISSUE TITLE
Can't Edit an Desc or Title on a WIP map...

### ISSUE THREAD

**Issue by A-plou** [beatmaps-io/beatsaver-main#70]
with the recent update with Tag, I cannot edit the title or the desc anymore. I forgot to put a title and now I can't publish it and the only way is to modiffied the map completely because even if I delete it, it say that the map already got publish.
In the pictures you can see the white box, but I try many times but I can't click on it.
![image](https://user-images.githubusercontent.com/73841814/150196824-dedb1022-3adf-468f-9eed-141ee286022d.png)

**Comment by Top-Cat** [comment]
Temporarily reverted the change to disabling the input boxes. Will fix their logic properly later
