### ISSUE TITLE
Beatsaver website map preview using 100% of cpu and really choppy when before months ago the preview did not do this and was not laggy.

### ISSUE THREAD

**Issue by TwinkieShip** [beatmaps-io/beatsaver-main#72]
![image](https://user-images.githubusercontent.com/73917095/150894908-0c5b5356-9dbe-46c7-8abe-36f09a5e2ade.png)

**Comment by Top-Cat** [comment]
The previewer is an external tool and not part of this repository

**Comment by TwinkieShip** [comment]
> The previewer is an external tool and not part of this repository
where do i get support for this then?
