### ISSUE TITLE
[Feature] Verified Mappers: UI Updates

### ISSUE THREAD

**Issue by helencarnate** [beatmaps-io/beatsaver-main#85]
**As a site user**, I want a clear visual indicator that a map is published by a verified mapper so that I can easily find them while browsing.

Maps from verified mappers could be marked with a #454088 bar on the map card. See mock below.
![image](https://user-images.githubusercontent.com/57695406/158286221-9e559ebe-ee77-4c97-a8ab-d09417c70ece.png)

Maps from verified mappers could be marked with a #454088 bar on the map info box on the map detail page. See mock below.
![image](https://user-images.githubusercontent.com/57695406/158286982-e2a465fb-5fd1-441e-ae61-e6ab48ffa3c1.png)

If a verified map has ANY other status (curated, qualified, ranked, or combination) the other status color replaces the verified color vs. trying to make some sort of gradient work.

**As a site user**, I want a clear visual indicator that a mapper is verified on their profile page. Mock to come.

**Comment by Top-Cat** [comment]
The bar has been added to cards in de725c6
Profile page may want to be its own work as part of the profile page rework?

**Comment by helencarnate** [comment]
I can absolutely include verified status with other profile page work. Thanks!
