### ISSUE TITLE
[Request] AI detection for Lolighter

### ISSUE THREAD

**Issue by Loloppe** [beatmaps-io/beatsaver-main#87]
Hello, I have remade my program for Beat Saber (https://github.com/Loloppe/Lolighter) from scratch not long ago, and since I'm making a brand new and extremely simple to use automapper, I was thinking that it would be preferable to add something specific to the difficulty.dat, info.dat, or even audio file generated by the program (or even all of them maybe) so that beatsaver catch it as autogenerated.

My old one as been out for a while and I know a few people that have been uploading on beatsaver with it without getting caught as AI (luckily not too many people, most of them aren't even using it anymore).

Please let me know what to do/ if it's doable. You can contact me on discord at Loloppe#6435, or here :)

**Comment by Top-Cat** [comment]
Without going too far into it the current screening system tries not to rely on any hidden information that the user could just remove.

You're already adding the _editors customData which is the best way to mark that your application was used in the process.

Any recommendation I would give (and equally any changes you make at this point) would just point people at what to reverse.

**Comment by Loloppe** [comment]
I understand. Using the _editors tag for any kind of detection seems like a pretty bad idea since my program doesn't just autogenerate map (unless I were to add some kind specification to it).

I don't personally think that most people would be determined enough to search the code or search in the json manually to find what would cause the detection, or at least it would catch most of them. I just think that it would be better to have something (even if it's easy to reverse/remove) than none.

I'll close this for now 👍
