### ISSUE TITLE
[Request] Add a way to "subscribe" to a mapper

### ISSUE THREAD

**Issue by Tootieee** [beatmaps-io/beatsaver-main#9]
It'd be nice to have a subscription area similar to youtube in which you subscribe to a mapper, possibly receive notifications for new uploads, and have a separate area where you could see new maps from people you're subscribed to. There doesn't need to be a subscriber count for a mapper, so there's no competitive reason for it. Just something convenient to be able to easily download new maps from your favorite mappers in a single page. Similar to a mod called BeatSync I believe but in browser

**Comment by helencarnate** [comment]
Completed on September 8, 2022 with Pull #157 (Followed Mappers)
