### ISSUE TITLE
A way to easily tell if maps contain arc or chain notes

### ISSUE THREAD

**Issue by EmyteShark** [beatmaps-io/beatsaver-main#91]
A note or warning on these maps as they will not be playable on earlier versions.

**Comment by Top-Cat** [comment]
1.20 is moddable on both PC and Quest, can load v2 and v3 maps.

The only reason I can even think of right now to be on an earlier version is maybe scoresaber in which case just stick to ranked maps (v3 maps are unrankable). And I expect it will be on the latest version soon after which there will be no reason to downgrade.

I don't see the point in investing time into this just for people downgrading.
