### ISSUE TITLE
Allow playlists to be opened in a new tab

### ISSUE THREAD

**Issue by helencarnate** [beatmaps-io/beatsaver-main#92]
As a site user, I want to be able to right click on a playlist from a users Playlists tab and open the detail page in a new tab (or copy the link).

Current experience does not give the "Open link in new tab" or "Copy link address" options when right-clicked
![image](https://user-images.githubusercontent.com/57695406/159145506-df958f28-8841-4571-b182-dbd88e28210a.png)

**Comment by Top-Cat** [comment]
Not possible with tables and the bootstrap styling and layout here is only for tables.

**Comment by helencarnate** [comment]
Time to redesign the playlist tab and make more work for Pixel, then 😈. Closing.
