### ISSUE TITLE
BeatSaverDownloader lag

### ISSUE THREAD

**Issue by MatthewYeetingSticks** [beatmaps-io/beatsaver-main#97]
I have noticed that with beatsaverdownloader i have been just frame dropping with stutters and it just hard capping at 60 frames in songs i figured out that beatsaverdownloader was the problem by deleting beatsaverdownloader and downloading kinsis bettersongsearch and now i'm always getting 120 hz

**Comment by Top-Cat** [comment]
This is not beat saver downloader
